### ISSUE TITLE
Cannot run IMAP platforme simulation scenario after Gatling version update

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-gatling#145]
```
15:30:26.101 [GatlingSystem-akka.actor.default-dispatcher-12] ERROR c.l.g.i.protocol.command.IdleHandler - Actor com.linagora.gatling.imap.protocol.command.IdleHandler@fe034ff crashed on message Some(Idle(UserId(27)))
com.yahoo.imapnio.async.exception.ImapAsyncClientException: failureType=OPERATION_PROHIBITED_ON_CLOSED_CHANNEL,sId=28,uId=ImapSession
	at com.yahoo.imapnio.async.internal.ImapAsyncSessionImpl.execute(ImapAsyncSessionImpl.java:307)
	at com.yahoo.imapnio.async.internal.ImapAsyncSessionImpl.execute(ImapAsyncSessionImpl.java:283)
	at com.linagora.gatling.imap.protocol.command.IdleHandler$$anonfun$receive$1.applyOrElse(IdleHandler.scala:42)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
15:30:26.101 [GatlingSystem-akka.actor.default-dispatcher-7] ERROR akka.actor.OneForOneStrategy - failureType=OPERATION_PROHIBITED_ON_CLOSED_CHANNEL,sId=28,uId=ImapSession
com.yahoo.imapnio.async.exception.ImapAsyncClientException: failureType=OPERATION_PROHIBITED_ON_CLOSED_CHANNEL,sId=28,uId=ImapSession
	at com.yahoo.imapnio.async.internal.ImapAsyncSessionImpl.execute(ImapAsyncSessionImpl.java:307)
	at com.yahoo.imapnio.async.internal.ImapAsyncSessionImpl.execute(ImapAsyncSessionImpl.java:283)
	at com.linagora.gatling.imap.protocol.command.IdleHandler$$anonfun$receive$1.applyOrElse(IdleHandler.scala:42)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Cc @Arsnael

**Comment by chibenwa** [comment]
Maybe unreleated. It looks like some login commands fails and leave the connection unusable
